---
- hosts: all
  remote_user: root
  vars:
       members: "{{ groups['nodes'] }}"
       etcd_version: "3.2.7"
  tasks:
  - name: Remove any old existing etcd
    shell: |
         yum -y install wget
         yum remove etcd etcd2 etcd3
         rpm -e `rpm -qa | grep etcd`
    ignore_errors: yes
  - name: Set up persistent directory
    shell: |
         mkdir -p /var/lib/etcd
         chown -R root:root /var/lib/etcd
         chmod -R a+rw /var/lib/etcd
  - name: Install new etcd
    shell: |
         wget https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
         mkdir /tmp/etcd
         tar xzvf etcd-v{{ etcd_version }}-linux-amd64.tar.gz -C /tmp
         cd /tmp/etcd-v{{ etcd_version }}-linux-amd64
         mv etcd etcdctl /usr/local/bin
         chmod 755 /usr/local/bin/etcd /usr/local/bin/etcdctl
  - template:
       src: ./etcd3.service.js
       dest: /etc/systemd/system/etcd3.service
       owner: root
       group: root
       mode: 0644
  - name: Reload and start the services
    shell: |
       systemctl daemon-reload
       systemctl enable etcd3.service
       systemctl start  etcd3.service
